#!/usr/bin/env bash

session() {
	tmux new-session -ds "$1" -c "$2" "$(which nvim) ."
	tmux new-window -t "$1" -dc "$2"
	tmux new-window -t "$1" -dc "$2"
}

selected="$1"

if [[ $# -ne 1 ]]; then
	selected="$(find ~/personal ~/.config ~/pkg ~ -maxdepth 1 -mindepth 1 -type d | fzf)"
fi

if [[ -z $selected ]]; then
	exit 130
fi

name="$(basename $selected | tr . _)"

if [[ -z $TMUX ]]; then
	session "$name" "$selected"
	tmux attach-session -t "$name"
else
	if ! tmux has-session -t "$name" 2> /dev/null; then
		session "$name" "$selected"
	fi

	tmux switch-client -t "$name"
fi
